import { Header } from '@/components/Header'
import './globals.css'
import { Roboto } from 'next/font/google'
import { Footer } from '@/components/Footer'
import { ReactNode } from 'react'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'John Code',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br" className={roboto.className}>
      <body className="bg-stone-100">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
